"""
sulcus.ingestion
================

The Ears of the system.

A *connector* is a small adapter that knows how to turn one external
operational surface into a stream of canonical ``IngestionEvent`` objects.
v1 shipped three hardcoded mock connectors (Slack/GitHub/CRM) replaying a
fixed three-tick script. v2 replaces that with a single ``SupabaseConnector``
that polls the live NovaCorp ``events`` table generated by ``generator.py`` --
the abstraction (``BaseConnector`` / ``IngestionStream``) is unchanged, only
where the events come from.

The ``IngestionStream`` is still the append-only log that fans connectors
together and exposes the corpus the evaluation loop (``guardrails.py``)
grounds against -- that interface is untouched so Gate 1 / Gate 2 / the
circadian loop keep working exactly as before.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from datetime import datetime
from typing import Dict, List, Optional

from .schemas import IngestionEvent, SourceSystem

# Maps the 12 real NovaCorp source systems onto the 3 broad ingestion
# categories the evaluation loop reasons about.
_SOURCE_CATEGORY = {
    "slack": SourceSystem.COMMUNICATION,
    "gmail": SourceSystem.COMMUNICATION,
    "outlook": SourceSystem.COMMUNICATION,
    "github": SourceSystem.EXECUTION,
    "jira": SourceSystem.EXECUTION,
    "pagerduty": SourceSystem.EXECUTION,
    "datadog": SourceSystem.EXECUTION,
    "salesforce": SourceSystem.OPERATIONS,
    "confluence": SourceSystem.OPERATIONS,
    "figma": SourceSystem.OPERATIONS,
    "workday": SourceSystem.OPERATIONS,
    "notion": SourceSystem.OPERATIONS,
}


def _row_to_event(row: dict) -> IngestionEvent:
    """Convert one Supabase ``events`` row into a canonical IngestionEvent."""
    raw_source = row.get("source", "slack")
    category = _SOURCE_CATEGORY.get(raw_source, SourceSystem.COMMUNICATION)
    created_at = row.get("created_at")
    if isinstance(created_at, str):
        timestamp = datetime.fromisoformat(created_at.replace("Z", "+00:00"))
    elif isinstance(created_at, datetime):
        timestamp = created_at
    else:
        timestamp = datetime.utcnow()

    tags = list(row.get("tags") or [])
    tags.append(f"dept:{row.get('department', 'Unknown')}")
    tags.append(f"risk:{row.get('risk_level', 'low')}")

    return IngestionEvent(
        event_id=str(row["id"]),
        tick=int(row["tick"]),
        timestamp=timestamp,
        source=category,
        channel=raw_source,
        user=row.get("actor", "Unknown"),
        text=row.get("content", ""),
        tags=tags,
    )


class BaseConnector(ABC):
    """Common interface for every ingestion source."""

    source: SourceSystem
    name: str

    @abstractmethod
    def poll(self, tick: int) -> List[IngestionEvent]:
        """Return the events this connector emits *on entering* ``tick``."""
        raise NotImplementedError

    def healthcheck(self) -> Dict[str, str]:
        return {"connector": self.name, "source": str(self.source), "status": "LIVE"}


class SupabaseConnector(BaseConnector):
    """Polls the live NovaCorp ``events`` table for a given tick."""

    source = SourceSystem.OPERATIONS  # mixed; per-row category is resolved below
    name = "supabase://novacorp/events"

    def __init__(self, client: Optional[object] = None) -> None:
        if client is None:
            from supabase_client import get_supabase_client

            client = get_supabase_client()
        self.client = client

    def poll(self, tick: int) -> List[IngestionEvent]:
        if self.client is None:
            return []
        try:
            resp = (
                self.client.table("events")
                .select("*")
                .eq("tick", tick)
                .eq("is_tombstoned", False)
                .order("created_at")
                .execute()
            )
        except Exception:
            return []
        rows = resp.data or []
        return [_row_to_event(r) for r in rows]

    def healthcheck(self) -> Dict[str, str]:
        status = "LIVE" if self.client is not None else "OFFLINE"
        return {"connector": self.name, "source": "supabase", "status": status}


class IngestionStream:
    """Append-only fan-in log across every connector.

    Holds the full immutable history plus a ``tombstones`` set used by the
    circadian loop to mark events whose long-term vectors have been garbage
    collected (the events stay in the audit log; they simply stop influencing
    the live knowledge graph).
    """

    def __init__(self, connectors: Optional[List[BaseConnector]] = None) -> None:
        self.connectors: List[BaseConnector] = connectors or [SupabaseConnector()]
        self.events: List[IngestionEvent] = []
        self.tombstones: set[str] = set()

    # -- ingestion -------------------------------------------------------- #
    def ingest_tick(self, tick: int) -> List[IngestionEvent]:
        """Poll every connector for ``tick`` and append new events."""
        new: List[IngestionEvent] = []
        seen_ids = {e.event_id for e in self.events}
        for connector in self.connectors:
            for ev in connector.poll(tick):
                if ev.event_id in seen_ids:
                    continue
                self.events.append(ev)
                new.append(ev)
                seen_ids.add(ev.event_id)
        return new

    # -- queries used by the evaluation loop ------------------------------ #
    def active_events(self) -> List[IngestionEvent]:
        """Events still influencing the live knowledge graph (not tombstoned)."""
        return [e for e in self.events if e.event_id not in self.tombstones]

    def corpus(self) -> str:
        """Lower-cased concatenation of active event text -- the grounding set."""
        return " \n ".join(e.text.lower() for e in self.active_events())

    def tombstone(self, event_ids: List[str]) -> None:
        self.tombstones.update(event_ids)

    def as_records(self) -> List[dict]:
        """Rows for the raw ephemeral event ticker (reverse chronological)."""
        rows = []
        for e in sorted(self.events, key=lambda x: x.timestamp, reverse=True):
            gc = " (GC)" if e.event_id in self.tombstones else ""
            rows.append(
                {
                    "Time": e.timestamp.strftime("%H:%M"),
                    "Source": e.channel,
                    "User": e.user,
                    "Event Text": e.text + gc,
                }
            )
        return rows
